services:
  - type: web
    name: primer-pcr-app
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production 